version: '3'

services:
  ui:
    image: nginx:1.17.8-alpine
    volumes:
      - ./ui:/usr/share/nginx/html
    ports:
      - 80:80
    depends_on:
      - api_gateway
  api_gateway:
    image: mcr.microsoft.com/dotnet/core/aspnet:2.2
    volumes:
      - ./api_gateway:/app
    working_dir: /app
    command: dotnet "MicroservicesOnDocker.ApiGateway.dll"
    ports:
      - 5000:80
    depends_on:
      - school_service
      - income_service
  school_service:
    image: mcr.microsoft.com/dotnet/core/aspnet:2.2
    volumes:
      - ./school_service:/app
    working_dir: /app
    command: dotnet "MicroservicesOnDocker.School.Api.dll"
  income_service:
    image: mcr.microsoft.com/dotnet/core/aspnet:2.2
    volumes:
      - ./income_service:/app
    working_dir: /app
    command: dotnet "MicroservicesOnDocker.Income.Api.dll"